### ISSUE TITLE
Remote SSH cannot connect to SDC VMs

### ISSUE THREAD

**Issue by kdotwei** [NYCU-SDC/front-end-training#3]
## Issue
Remote SSH cannot connect to the SDC VMs.

## Possible Problems
I trace the `install.sh` in the code-server installation script.
I found it will get stuck while doing the `curl` to https://github.com/coder/code-server/releases/latest.

**Comment by kdotwei** [comment]
# Alternative Solutions
Please use the SFTP extension to address the current issue as a temporary solution. This extension allows you to synchronize files between your local machine and a remote server using the SFTP protocol, providing a convenient way to transfer files securely.

## 1. Make a directory on your local computer to sync data on the server.
>[!NOTE]
>You can make this directory anywhere and with any name on your computer.
## 2. Open this directory with VSCode.
## 3. Install this extension.
>[!IMPORTANT]
>The author is **Satiro Marra**! 

![](https://i.imgur.com/aWAmapu.png)

## 4. Make a config file
1. Open the command box with `ctrl`+`shift`+`p`  in VSCode. (Box with `>` symbol.)
2. Type `sftp` and select the `SFTP: config`
![](https://i.imgur.com/KADzzkC.png)

## 5. Complete this config file.
![](https://i.imgur.com/HcniR2H.png)

### **Name**
`sdc-id` is your VM ID with the tag `sdc`. 
> [!TIP]
> When you log into your VM, you'll get this message on the terminal: `ansible@vm-id`.

### **Host**
The host is your server IP.

### **Username**
The login username. It is `ansible` on your VM.

### **Remote Path**
It is the path on the server you want to synchronize down to your computer.

### **Ignore remote files/folders**
> [!CAUTION]
> Only `.vscode` here!

### **Private Key**
The private key path is `~/.ssh/id_sdc_300a10` and replaces `~` with the absolute path.
> [!TIP]
> If you forget the absolute path of `~`, you can `cd` to `~` and `pwd` to get the absolute path.

**And save it.**
![](https://i.imgur.com/DsjfX2n.png)

> [!NOTE]
> You don't need to change other settings.

## 6. Sync Both
Open the command box with `ctrl`+`shift`+`p`  in VSCode again.
And type `sftp`, and select the `SFTP: Sync Both Dirctions`.
![](https://i.imgur.com/uJ3ZY5t.png)

## 7. Developing!

You can develop locally, and the SFTP extension will sync your work automatically now.

**Comment by amandahsieh** [comment]
If you encountered any problem, you are welcomed to paste the process and the current status in the comment.

**Comment by kdotwei** [comment]
Live discussion channel: Discord channel [front-end-training](https://discord.com/channels/738258665135538228/1198426900784218133/1223533697978994709)

**Comment by kdotwei** [comment]
# Solution
We change the MTU of each VM's interfaces, and @steveyiyo changes the mss on his router.
All discussions are on the live channel [front-end-training](https://discord.com/channels/738258665135538228/1223533697978994709).
